import createClient from "openapi-fetch"

import type { components, paths } from "./schema"

/** Client typé de l'API MyMaestro (types générés depuis server/openapi.json). */
export const api = createClient<paths>({ baseUrl: "" })

export type Schemas = components["schemas"]
export type Sante = Schemas["Sante"]
export type ResumeProjet = Schemas["ResumeProjet"]
export type Projet = Schemas["Projet"]
export type Plan = Schemas["Plan"]
export type Timeline = Schemas["Timeline"]
export type Recette = Schemas["Recette"]
export type FicheBibliotheque = Schemas["FicheBibliotheque"]
export type ImageFiche = Schemas["ImageFiche"]
export type TypeFiche = Schemas["TypeFiche"]
export type RoleImageFiche = Schemas["RoleImageFiche"]
export type EtatFile = Schemas["EtatFile"]
export type Job = Schemas["Job"]
export type EtatConnecteur = Schemas["EtatConnecteur"]
export type EtatMoteurInstalle = Schemas["EtatMoteurInstalle"]
export type ManifesteModule = Schemas["ManifesteModule"]
export type InfosRendu = Schemas["InfosRendu"]
export type EtatPhase = Schemas["EtatPhase"]
export type EtatDirector = Schemas["EtatDirector"]
export type Analyse = Schemas["Analyse"]
export type Section = Schemas["Section"]
export type LigneParoles = Schemas["LigneParoles"]
export type Brief = Schemas["Brief-Output"]
export type Concept = Schemas["Concept"]
export type MessageChat = Schemas["MessageChat"]
export type CompatibiliteMoteur = Schemas["CompatibiliteMoteur"]
export type PlanModification = Schemas["PlanModification"]
export type MoteurVideo = Schemas["MoteurVideo"]
export type MoteurImage = Schemas["MoteurImage"]
export type Clip = Schemas["Clip"]
export type Prise = Schemas["Prise"]
export type SortiePostProd = Schemas["SortiePostProd"]
export type Segment = Schemas["Segment"]
export type ClipModification = Schemas["ClipModification"]
export type ActionProgrammee = Schemas["ActionProgrammee"]
export type ActionEntree = Schemas["ActionEntree"]
export type TypeAction = Schemas["TypeAction"]
export type EtatClip = Schemas["EtatClip"]
export type ExportProjet = Schemas["ExportProjet"]
export type EstimationVideo = Schemas["EstimationVideo"]
export type Nettoyage = Schemas["Nettoyage"]
export type TypePiste = Schemas["TypePiste"]
